travis:
  secure:
    BINSTAR_TOKEN: M6LuwD4/M7NSVgdf6boDAZsN9C/nE+lQrsTOWMDdALaCwwjy7kszBtM9tVcOWB3CvEYPQc8tIqU8JoRe7ClTf6p/z2+0NGK3fVlSSpzndHY8uWp5r8TGNbk5lTvdfRELaeaUxNxy49jgk4mg9ZnPGqB7nd79EUkjvyIwXCySXNJ/MH3ClXQEkbABrE0hb9xfne/qXSEBENPpwSXBTTv2+vv57J04NsuTvzwVIr7rs6L9r5nvYhyz+/dvueusE0N71nH8uzMU8C2kc4BeygvlA+soT6vYPSg4eUrnwkz7yDrH231ttRrI47tHsQa/QZg5fILDrJqylyUFnqC70dla/ByOmnnLdovOmMfmjC1jX59D2kpKAyTOmuVPz30S8MIZi0Wk/FnpR76rDixl+CkUCiywuwyQBM25eqc3qe3pn3r7QKNP1anwhEjG2ezdjM5s3ZXHyx+Dld6sGiLLd4LD/5kDWyyaNP3ZdfWfNW7wPpRqliB76I42L4GmJkNW1Ymxw0Z2BNySjRC3o8YQ12gKjntG2SYBSapMRTbTxmwgnjcgYBThYW9TpiH1rNH2CkGJyZNKebaXM/m8gDvKw8WKQoAJy08ABSZF4eCAsOnwapyRqFZXsgM3RCceaG8LdVjXxCbtOLMFf9ydXS/++jF1hbW0YPDpGWOoeMinxBSAMkg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
